#!/usr/bin/env python
# Since the gsm database is not reachable afaik, I decided to use the existing wrapper to just copy the right sky
# model in place

import sys
from shutil import copyfile

fnam = sys.argv[1]

copyfile("/usr/share/data_skymodel.sky", fnam)
